config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/dashboard' => "web_reports#index", as: :reports_dash
  get '/reports/wpscan' => "web_reports#wpscan_report", as: :wpscans_report
  get '/reports/whatweb' => "web_reports#whatweb_report", as: :whatwebs_report
  get '/reports/google_business_malware' => "web_reports#malware_report", as: :google_malware_report
  get '/reports/semrush_report' => "web_reports#semrush_report", as: :web_semrush_report
  get '/set_claim/:id' => "web_reports#set_claim_lead", as: :set_claim
  post '/create_lead_comment' => "leads#add_comment", as: :add_comment
  get '/reports/semrush/:campaign' => "semrush#index"

  #post '/tools/whatweb', to: 'whatweb#tools'

  match '/wizard/step2', to: 'wizard#step2', as: 'step2', via: [:get, :post]
  match '/wizard/step3', to: 'wizard#step3', as: 'step3', via: [:get, :post]
  match '/wizard/step4', to: 'wizard#step4', as: 'step4', via: [:get, :post]

  match '/tools/address2gps', to: 'tools#address2gps', as: 'address2gps', via: [:get, :post]
  match '/tools/placeids', to: 'tools#placeids', as: 'placeids', via: [:get, :post]
  match '/tools/placedetails', to: 'tools#placedetails', as: 'placedetails', via: [:get, :post]

  match '/tools/arachni', to: 'tools#arachni', as: 'arachni', via: [:get, :post]
  match '/tools/skipfish', to: 'tools#skipfish', as: 'skipfish', via: [:get, :post]
  match '/tools/w3af', to: 'tools#w3af', as: 'w3af', via: [:get, :post]
  match '/tools/wapiti', to: 'tools#wapiti', as: 'wapiti', via: [:get, :post]
  match '/tools/whatweb', to: 'tools#whatweb', as: 'whatweb', via: [:get, :post]
  match '/tools/wpscan', to: 'tools#wpscan', as: 'wpscan', via: [:get, :post]

  root to: 'web_reports#index'

  resources :leads
  resources :comments
  

  devise_for :users

  resources :users
  resources :businesses
  resources :place_details, only: :index
  resources :semrush_paid_reports,only: :index
  resources :wizard

  scope module: :api, defaults: {format: :json} do
      namespace :v1 do
        resources :whatwebs,only: :index
        resources :wpscans,only: :index
        resources :joomscans,only: :index
        resources :semrush_paid_reports,only: :index
        resources :arachni,only: :index
        resources :semrush_paid_reports,only: :index

      end
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment_body, :commentable_id, :commentable_type)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment_body %><br>
    <%= f.text_field :comment_body %>
  </div>
  <div class="field">
    <%= f.label :commentable_id %><br>
    <%= f.text_field :commentable_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment body</th>
      <th>Commentable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment_body %></td>
        <td><%= comment.commentable %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment body:</strong>
  <%= @comment.comment_body %>
</p>

<p>
  <strong>Commentable:</strong>
  <%= @comment.commentable %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>