config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/dashboard' => "web_reports#index", as: :reports_dash
  get '/reports/wpscan' => "web_reports#wpscan_report", as: :wpscans_report
  get '/reports/whatweb' => "web_reports#whatweb_report", as: :whatwebs_report
  get '/reports/google_business_malware' => "web_reports#malware_report", as: :google_malware_report
  get '/reports/semrush_report' => "web_reports#semrush_report", as: :web_semrush_report
  get '/set_claim/:id' => "web_reports#set_claim_lead", as: :set_claim
  post '/create_lead_comment' => "leads#add_comment", as: :add_comment
  get '/reports/semrush/:campaign' => "semrush#index"

  #post '/tools/whatweb', to: 'whatweb#tools'

  match '/wizard/step2', to: 'wizard#step2', as: 'step2', via: [:get, :post]
  match '/wizard/step3', to: 'wizard#step3', as: 'step3', via: [:get, :post]
  match '/wizard/step4', to: 'wizard#step4', as: 'step4', via: [:get, :post]

  match '/tools/address2gps', to: 'tools#address2gps', as: 'address2gps', via: [:get, :post]
  match '/tools/placeids', to: 'tools#placeids', as: 'placeids', via: [:get, :post]
  match '/tools/placedetails', to: 'tools#placedetails', as: 'placedetails', via: [:get, :post]

  match '/tools/arachni', to: 'tools#arachni', as: 'arachni', via: [:get, :post]
  match '/tools/skipfish', to: 'tools#skipfish', as: 'skipfish', via: [:get, :post]
  match '/tools/w3af', to: 'tools#w3af', as: 'w3af', via: [:get, :post]
  match '/tools/wapiti', to: 'tools#wapiti', as: 'wapiti', via: [:get, :post]
  match '/tools/whatweb', to: 'tools#whatweb', as: 'whatweb', via: [:get, :post]
  match '/tools/wpscan', to: 'tools#wpscan', as: 'wpscan', via: [:get, :post]

  root to: 'web_reports#index'

  resources :leads
  resources :comments
  

  devise_for :users

  resources :users
  resources :businesses
  resources :place_details, only: :index
  resources :semrush_paid_reports,only: :index
  resources :wizard

  scope module: :api, defaults: {format: :json} do
      namespace :v1 do
        resources :whatwebs,only: :index
        resources :wpscans,only: :index
        resources :joomscans,only: :index
        resources :semrush_paid_reports,only: :index
        resources :arachni,only: :index
        resources :semrush_paid_reports,only: :index

      end
    end
end

app/models/lead.rb
class Lead < ActiveRecord::Base
	has_many :comments, as: :commentable, dependent: :destroy
	# accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @search = Lead.order(:vulnerability_count => 'desc').includes(:comments).search(params[:q])
    @leads = @search.result.page(params[:page]).per(10)
    @path = leads_path
  end
  def add_comment
    @comment =Comment.create(comment_body: params[:comment_body])
    if @comment.save!
      Lead.find_by_id(params[:lead_id]).comments << @comment
    end
    redirect_to :back
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to leads_path, notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to leads_path, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:url, :formatted_address, :phone_number, :vulnerability_count)
    end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :formatted_address %><br>
    <%= f.text_field :formatted_address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :vulnerability_count %><br>
    <%= f.number_field :vulnerability_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads/_search_filters.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="header">
        <%= search_form_for @search, url: @path, method: :get do |f|%>
          <div class="row">

            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :url_cont, "Url"%>
                <%= f.text_field :url_cont, :class=> 'form-control'%>
              </div>
            </div>

            <div class="col-md-2">
              <br/>
              <%= f.submit 'Search',  :class=> 'btn btn-primary pull-right'%>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>

<style type="text/css">
  .modal-body {
    max-height:calc(100vh - 150px);
    overflow-y:auto;
    overflow-x:auto;
  }
</style>
<div class="panel panel-warning">
  <div class="panel-heading">Leads - Total <%= @leads.count %><%= link_to 'New Lead', new_lead_path, class: "pull-right"%></div>
  <%= render 'search_filters' %>
  <div class="panel-body">
    <table class="table table-condensed table-bordered">
      <thead>
        <tr>
          <th>Url</th>
          <th>Formatted address</th>
          <th>Phone number</th>
          <th>Issues</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @leads.each_with_index do |lead, index| %>
          <tr style="display: none;">
            <td>
              <div id="lead-comments<%=index%>"> 
                <table class="table table-condensed table-stripped">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Comment</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% lead.comments.each_with_index do |lead_comment, i| %>
                      <tr>
                        <td><%= i %></td>
                        <td>
                          <%= lead_comment.comment_body %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <%if lead.url.present? %>
                <%= link_to lead.url, lead.url, target: "_blank" %>
              <%end%>
            </td>
            <td><%= lead.formatted_address %></td>
            <td><%= lead.phone_number %></td>
            <td><%= lead.vulnerability_count %></td>
            <td>
              <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" id="comments" data-id="lead-comments<%=index%>" data-toggle="modal" data-target="#myModal" class="btn btn-sm btn-info <%=lead.comments.count == 0 ? 'disabled': '' %>">View <%= pluralize(lead.comments.count, "Comment")%></button>
                <button type="button" id="add-lead-comments" data-leadid= "<%=lead.id%>" data-toggle="modal" data-target="#add-comment-modal" class="btn btn-sm btn-success">Add Comments</button>
              </div>
              <div class="btn-group" role="group">
                <%= link_to 'Edit', edit_lead_path(lead), class: "btn btn-sm btn-warning"%>
                <%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer"><%= paginate @leads %></div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Lead Comments</h4>
      </div>
      <div class="modal-body" id="view-comments" style="font-family: monospace; white-space: pre;">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="add-comment-modal" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add Comment</h4>
      </div>
      <div class="modal-body" style="font-family: monospace; white-space: pre;">
        <%= form_tag(add_comment_path, :method => "POST", :class => "form-inline") do |f| %>
          <div class="form-group">
            <%= label_tag :comment_body %>
            <%= text_field_tag :comment_body, nil, :class => "form-control" %>
          </div>
          <div class="form-group">
            <%= submit_tag "Create", :class => "btn btn-success"%>
          </div>
          <%= hidden_field_tag 'lead_id', :value => "" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $("button#comments").click(function(e){
      $("#view-comments").html($("#"+$(this).attr("data-id")).html());
    });

    $("button#add-lead-comments").click(function(e){
      $("#lead_id").attr("value", $(this).attr("data-leadid"));    
    });
  });//end dom ready
</script>

app/views/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>