config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/dashboard' => "web_reports#index", as: :reports_dash
  get '/reports/wpscan' => "web_reports#wpscan_report", as: :wpscans_report
  get '/reports/whatweb' => "web_reports#whatweb_report", as: :whatwebs_report
  get '/reports/google_business_malware' => "web_reports#malware_report", as: :google_malware_report
  get '/reports/semrush_report' => "web_reports#semrush_report", as: :web_semrush_report
  get '/set_claim/:id' => "web_reports#set_claim_lead", as: :set_claim
  post '/create_lead_comment' => "leads#add_comment", as: :add_comment
  get '/reports/semrush/:campaign' => "semrush#index"

  #post '/tools/whatweb', to: 'whatweb#tools'

  match '/wizard/step2', to: 'wizard#step2', as: 'step2', via: [:get, :post]
  match '/wizard/step3', to: 'wizard#step3', as: 'step3', via: [:get, :post]
  match '/wizard/step4', to: 'wizard#step4', as: 'step4', via: [:get, :post]

  match '/tools/address2gps', to: 'tools#address2gps', as: 'address2gps', via: [:get, :post]
  match '/tools/placeids', to: 'tools#placeids', as: 'placeids', via: [:get, :post]
  match '/tools/placedetails', to: 'tools#placedetails', as: 'placedetails', via: [:get, :post]

  match '/tools/arachni', to: 'tools#arachni', as: 'arachni', via: [:get, :post]
  match '/tools/skipfish', to: 'tools#skipfish', as: 'skipfish', via: [:get, :post]
  match '/tools/w3af', to: 'tools#w3af', as: 'w3af', via: [:get, :post]
  match '/tools/wapiti', to: 'tools#wapiti', as: 'wapiti', via: [:get, :post]
  match '/tools/whatweb', to: 'tools#whatweb', as: 'whatweb', via: [:get, :post]
  match '/tools/wpscan', to: 'tools#wpscan', as: 'wpscan', via: [:get, :post]

  root to: 'web_reports#index'

  resources :leads
  resources :comments
  

  devise_for :users

  resources :users
  resources :businesses
  resources :place_details, only: :index
  resources :semrush_paid_reports,only: :index
  resources :wizard

  scope module: :api, defaults: {format: :json} do
      namespace :v1 do
        resources :whatwebs,only: :index
        resources :wpscans,only: :index
        resources :joomscans,only: :index
        resources :semrush_paid_reports,only: :index
        resources :arachni,only: :index
        resources :semrush_paid_reports,only: :index

      end
    end
end

app/models/place_detail.rb
# == Schema Information
#
# Table name: place_details
#
#  id                         :integer          not null, primary key
#  place_id                   :integer
#  name                       :string
#  google_id                  :string
#  google_place_id            :string
#  url                        :string
#  utc_offset                 :string
#  vicinity                   :string
#  website                    :string
#  international_phone_number :string
#  raw                        :text
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#

class PlaceDetail < ActiveRecord::Base
  belongs_to :place
end

app/controllers/place_details_controller.rb
class PlaceDetailsController < ApplicationController
  def index
    @search = PlaceDetail.search(params[:q])
    @place_details = @search.result.page(params[:page])
  end
end

app/views/place_details/_search_filters.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="header">
        <%= search_form_for @search, url: place_details_path, method: :get do |f|%>
          <div class="row">
            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :place_place_id_cont, "Place #"%>
                <%= f.text_field :place_place_id_cont,:class=>"form-control"%>
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :name_cont, "Name"%>
                <%= f.text_field :name_cont, :class=> 'form-control'%>
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :website_cont, "Website"%>
                <%= f.text_field :website_cont, :class=> 'form-control'%>
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :url_cont, "Url"%>
                <%= f.text_field :url_cont, :class=> 'form-control'%>
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :place_keyword_key_cont, "Keyword"%>
                <%= f.text_field :place_keyword_key_cont, :class=> 'form-control'%>
              </div>
            </div>
            <div class="col-md-2">
              <br/>
              <%= f.submit 'Search',  :class=> 'btn btn-primary pull-right'%>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/place_details/index.html.erb
<div class="jumbotron">
  <%= render 'search_filters' %>
  <p>Business Details</p>
  <table class="table table-condensed">
    <thead>
      <tr>
        <td>Place id</td>
        <td>Name</td>
        <td>Url</td>
        <td>Website</td>
        <td>Vicinity</td>
      </tr>
    </thead>
    <tbody>
      <%@place_details.each do |place_detail|%>
        <tr>
          <td><%= place_detail.place_id %></td>
          <td><%= place_detail.name %></td>
          <td><%= place_detail.url %></td>
          <td><%= place_detail.website %></td>
          <td><%= place_detail.vicinity %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>
<%= paginate @place_details %>