config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/dashboard' => "web_reports#index", as: :reports_dash
  get '/reports/wpscan' => "web_reports#wpscan_report", as: :wpscans_report
  get '/reports/whatweb' => "web_reports#whatweb_report", as: :whatwebs_report
  get '/reports/google_business_malware' => "web_reports#malware_report", as: :google_malware_report
  get '/reports/semrush_report' => "web_reports#semrush_report", as: :web_semrush_report
  get '/set_claim/:id' => "web_reports#set_claim_lead", as: :set_claim
  post '/create_lead_comment' => "leads#add_comment", as: :add_comment
  get '/reports/semrush/:campaign' => "semrush#index"

  #post '/tools/whatweb', to: 'whatweb#tools'

  match '/wizard/step2', to: 'wizard#step2', as: 'step2', via: [:get, :post]
  match '/wizard/step3', to: 'wizard#step3', as: 'step3', via: [:get, :post]
  match '/wizard/step4', to: 'wizard#step4', as: 'step4', via: [:get, :post]

  match '/tools/address2gps', to: 'tools#address2gps', as: 'address2gps', via: [:get, :post]
  match '/tools/placeids', to: 'tools#placeids', as: 'placeids', via: [:get, :post]
  match '/tools/placedetails', to: 'tools#placedetails', as: 'placedetails', via: [:get, :post]

  match '/tools/arachni', to: 'tools#arachni', as: 'arachni', via: [:get, :post]
  match '/tools/skipfish', to: 'tools#skipfish', as: 'skipfish', via: [:get, :post]
  match '/tools/w3af', to: 'tools#w3af', as: 'w3af', via: [:get, :post]
  match '/tools/wapiti', to: 'tools#wapiti', as: 'wapiti', via: [:get, :post]
  match '/tools/whatweb', to: 'tools#whatweb', as: 'whatweb', via: [:get, :post]
  match '/tools/wpscan', to: 'tools#wpscan', as: 'wpscan', via: [:get, :post]

  root to: 'web_reports#index'

  resources :leads
  resources :comments
  

  devise_for :users

  resources :users
  resources :businesses
  resources :place_details, only: :index
  resources :semrush_paid_reports,only: :index
  resources :wizard

  scope module: :api, defaults: {format: :json} do
      namespace :v1 do
        resources :whatwebs,only: :index
        resources :wpscans,only: :index
        resources :joomscans,only: :index
        resources :semrush_paid_reports,only: :index
        resources :arachni,only: :index
        resources :semrush_paid_reports,only: :index

      end
    end
end

app/views/reports/_search_filters.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="header">
        <%= search_form_for @search, url: semrush_paid_reports_path, method: :get do |f|%>
          <div class="row">

            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :url_cont, "Url"%>
                <%= f.text_field :url_cont, :class=> 'form-control'%>
              </div>
            </div>

            <div class="col-md-2">
              <br/>
              <%= f.submit 'Search',  :class=> 'btn btn-primary pull-right'%>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/reports/_semrush_search_filters.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="header">
        <%= search_form_for @search, url: semrush_paid_reports_path, method: :get do |f|%>
          <div class="row">
            
            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :url_cont, "Url"%>
                <%= f.text_field :url_cont, :class=> 'form-control'%>
              </div>
            </div>
            
            <div class="col-md-2">
              <br/>
              <%= f.submit 'Search',  :class=> 'btn btn-primary pull-right'%>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/reports/marketing.html.erb
<div class="jumbotron">
  <%= render 'search_filters' %>
  <p>Semrush Reports</p>
  <table class="table table-condensed">
    <thead>
      <tr>
        <td>URL</td>
        <td>Response</td>
      </tr>
    </thead>
    <tbody>
      <%@semrush_paid_reports.each do |semrush_paid_report|%>
        <tr>
          <td><%= semrush_paid_report.url %></td>
          <td><%= semrush_paid_report.response %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>
<%= paginate @semrush_paid_reports %>

app/views/reports/security.html.erb
<div class="jumbotron">
  <%= render 'search_filters' %>
  <p>Security Reports</p>
  <table class="table table-condensed">
    <thead>
      <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Address</td>
        <td>Phone Number</td>
        <td>Security Report</td>
        <td>Claim Lead</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>Johns Security</td>
        <td>123 New York City, NY, 12342</td>
        <td>424-111-1234</td>
        <td><a href="/reports/view/:id" onclick="alert('View Single Report')">View Report</a></td>
        <td><a href="" onclick="alert("Send to SugarCRM")">Claim Lead</a></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/reports/semrush_paid_reports.erb
<div class="jumbotron">
  <%= render 'semrush_search_filters' %>
  <p>Semrush Reports</p>
  <table class="table table-condensed">
    <thead>
      <tr>
        <td>URL</td>
        <td>Response</td>
      </tr>
    </thead>
    <tbody>
      <%@semrush_paid_reports.each do |semrush_paid_report|%>
        <tr>
          <td><%= semrush_paid_report.url %></td>
          <td><%= semrush_paid_report.response %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>
<%= paginate @semrush_paid_reports %>